version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/bookers2-advance
      - tmp-data:/bookers2-advance/tmp
    depends_on:
      - db
  db:
    platform: linux/x86_64 #m1だとこの記述が必要
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: nginx
    volumes:
      - public-data:/bookers2-advance/public
      - tmp-data:/bookers2-advance/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  db-data:
